import 'dart:math';

import '../services/api_service.dart';
import 'mock_seed.dart';

/// The in-app stand-in for the Laravel API.
///
/// It answers the same paths, with the same verbs and the same JSON shapes, so
/// [ApiService] can route to it in Phase 1 and to HTTP in Phase 2 without any
/// screen, controller or model changing.
class MockApi {
  MockApi() {
    _seed();
  }

  // ── the dataset ──
  final _users = <MockUser>[];
  final _departments = <MockDepartment>[];
  final _types = <MockVoucherType>[];
  final _vouchers = <MockVoucher>[];
  final _approvals = <MockApproval>[];
  final _notifications = <MockNotification>[];
  final List<MockStep> _steps = defaultSteps();

  int _nextVoucherId = 1,
      _nextApprovalId = 1,
      _nextNotificationId = 1,
      _nextCommentId = 1;

  MockUser? _current;

  /* The demo tenant. Every field here is one a company fills in under
     Branding — none of it is special-cased anywhere in the app. */
  static const _company = {
    'id': 1,
    'name': 'Watercom (T) Limited',
    'slug': 'watercom',
    'legal_name': 'WATERCOM (T) LIMITED',
    'email': 'info@watercom.co.tz',
    'phone': '+255 22 264 0831',
    'address': 'P.O. Box 20831, Kibada, Kisarawe II · Dar es Salaam, Tanzania',
    'website': 'www.watercom.co.tz',
    'tin': '109-482-771',
    'currency': 'TZS',
    'locale': 'en',
    'logo_url': 'assets/demo/watercom-logo.png',
    'logo_mark_url': 'assets/demo/watercom-mark.png',
    'bank_name': 'CRDB Bank',
    'bank_account_name': 'WATERCOM T LIMITED',
    'bank_account_number': '0250390569500',
    'bank_branch': 'Tower Branch',
    'primary_color': '#2E3192',
    'status': 'active',
    'is_usable': true,
    'is_expired': false,
    'days_remaining': 24,
    'trial_ends_at': null,
    'voucher_footer_text':
        'This voucher is computer generated by VouchFlow and is valid without a '
        'wet stamp. Retain the original for audit.',
    'plan': {
      'id': 2,
      'code': 'business',
      'name': 'Business',
      'label': 'Business',
      'blurb': 'Departments, branding and reporting for growing companies.',
      'price': 249000,
      'currency': 'TZS',
      'max_users': 50,
      'max_vouchers_per_month': null,
      'trial_days': 14,
      'features': [
        '50 users',
        'Unlimited vouchers',
        '3 approval levels',
        'Custom branding',
        'Reports & exports',
      ],
    },
  };

  /* ══════════════════════════════════════════════════════════ dispatch ══ */

  /// Answers one request. [path] never carries a query string.
  Future<dynamic> handle(
    String method,
    String path, {
    Map<String, dynamic> body = const {},
    Map<String, dynamic> query = const {},
  }) async {
    // A little latency, so loading states are exercised as they will be.
    await Future<void>.delayed(
      Duration(milliseconds: 120 + Random().nextInt(180)),
    );

    final seg = path.replaceFirst(RegExp(r'^/+'), '').split('/');

    if (method == 'POST' && path == '/auth/login') return _login(body);

    if (_current == null) {
      throw ApiException(401, 'Your session has ended. Sign in again.');
    }

    switch (path) {
      case '/auth/me':
        return {'user': _userJson(_current!), 'company': _company};
      case '/auth/logout':
        _current = null;
        return {'message': 'Signed out.'};
      case '/auth/change-password':
        if ('${body['current_password']}' != 'Password123!') {
          throw ApiException(422, 'That is not your current password.', {
            'current_password': ['That is not your current password.'],
          });
        }
        return {'message': 'Password updated.'};
      case '/profile':
        for (final key in ['locale', 'theme', 'name', 'job_title']) {
          final value = body[key];
          if (value == null) continue;
          if (key == 'locale') _current!.locale = '$value';
          if (key == 'theme') _current!.theme = '$value';
          if (key == 'job_title') _current!.jobTitle = '$value';
        }
        return {'data': _userJson(_current!)};
      case '/profile/signature':
        if (method == 'GET') return {'signature': _current!.signature};
        if (method == 'DELETE') {
          _current!.signature = null;
          return {'message': 'Signature removed.'};
        }
        _current!.signature = '${body['signature']}';
        return {'message': 'Signature saved.'};
      case '/dashboard':
        return _dashboard();
      case '/departments':
        return {
          'data': _departments
              .where((d) => d.companyId == _current!.companyId)
              .map(
                (d) => {
                  'id': d.id,
                  'name': d.name,
                  'cost_centre': d.costCentre,
                },
              )
              .toList(),
        };
      case '/voucher-types':
        return {
          'data': _types
              .where((t) => t.companyId == _current!.companyId)
              .map(
                (t) => {
                  'id': t.id,
                  'name': t.name,
                  'label': _current!.locale == 'sw' ? t.nameSw : t.name,
                  'next_number_preview': _previewNumber(t),
                },
              )
              .toList(),
        };
      case '/vouchers/pending':
        return {'data': _pending().map((v) => _voucherJson(v)).toList()};
      case '/notifications':
        final rows = _notifications
            .where((n) => n.userId == _current!.id)
            .toList();
        return {
          'data': rows.map(_notificationJson).toList(),
          'meta': {'unread_count': rows.where((n) => n.readAt == null).length},
        };
      case '/notifications/unread-count':
        return {
          'unread_count': _notifications
              .where((n) => n.userId == _current!.id && n.readAt == null)
              .length,
        };
      case '/notifications/read-all':
        var count = 0;
        for (final n in _notifications) {
          if (n.userId == _current!.id && n.readAt == null) {
            n.readAt = DateTime.now().toIso8601String();
            count++;
          }
        }
        return {'count': count};
    }

    if (seg.first == 'notifications' && seg.length == 3 && seg[2] == 'read') {
      final id = int.tryParse(seg[1]);
      for (final n in _notifications) {
        if (n.id == id) n.readAt = DateTime.now().toIso8601String();
      }
      return {
        'data': {'id': id},
      };
    }

    if (path == '/vouchers' && method == 'GET') return _index(query);
    if (path == '/vouchers' && method == 'POST') return _create(body);

    if (seg.first == 'vouchers' && seg.length >= 2) {
      final id = int.tryParse(seg[1]);
      if (id == null) throw ApiException(404, 'Voucher not found.');
      final voucher = _find(id);

      if (seg.length == 2 && method == 'GET') {
        return {'data': _voucherJson(voucher, detailed: true)};
      }
      if (seg.length == 2 && method == 'PUT') return _update(voucher, body);
      if (seg.length == 2 && method == 'DELETE') {
        _vouchers.removeWhere((v) => v.id == id);
        return {'message': 'Draft deleted.'};
      }
      if (seg.length == 3 && method == 'POST') {
        return _act(voucher, seg[2], body);
      }
    }

    throw ApiException(404, 'No mock route for $method $path');
  }

  /* ═══════════════════════════════════════════════════════════ actions ══ */

  Map<String, dynamic> _login(Map<String, dynamic> body) {
    final email = '${body['email'] ?? ''}'.trim().toLowerCase();
    final user = _users.where((u) => u.email == email).firstOrNull;
    if (user == null || '${body['password']}' != 'Password123!') {
      throw ApiException(422, 'These credentials do not match our records.', {
        'email': ['These credentials do not match our records.'],
      });
    }
    _current = user;
    return {
      'token': 'mock-${user.id}-${DateTime.now().millisecondsSinceEpoch}',
      'user': _userJson(user),
      'company': _company,
    };
  }

  Map<String, dynamic> _index(Map<String, dynamic> query) {
    var rows = _visible().toList();

    final scope = '${query['scope'] ?? 'all'}';
    if (scope == 'mine') {
      rows = rows.where((v) => v.requesterId == _current!.id).toList();
    } else if (scope == 'pending') {
      rows = _pending();
    }

    final status = query['status'];
    if (status != null && '$status'.isNotEmpty && status != 'all') {
      rows = switch ('$status') {
        'pending' => rows.where((v) => v.status == 'in_review').toList(),
        'drafts' => rows.where((v) => v.status == 'draft').toList(),
        final s => rows.where((v) => v.status == s).toList(),
      };
    }
    if (query['kind'] != null && '${query['kind']}'.isNotEmpty) {
      rows = rows.where((v) => v.kind == '${query['kind']}').toList();
    }

    final q = '${query['q'] ?? ''}'.trim().toLowerCase();
    if (q.length > 1) {
      rows = rows.where((v) {
        final requester = _user(v.requesterId)?.name ?? '';
        return '${v.number}${v.purpose}${v.payee}$requester'
            .toLowerCase()
            .contains(q);
      }).toList();
    }

    rows.sort((a, b) => b.voucherDate.compareTo(a.voucherDate));

    final perPage = int.tryParse('${query['per_page'] ?? 20}') ?? 20;
    final page = int.tryParse('${query['page'] ?? 1}') ?? 1;
    final start = (page - 1) * perPage;
    final slice = rows.skip(start).take(perPage).toList();

    return {
      'data': slice.map((v) => _voucherJson(v)).toList(),
      'meta': {
        'current_page': page,
        'last_page': (rows.length / perPage).ceil().clamp(1, 9999),
        'per_page': perPage,
        'total': rows.length,
        'total_amount': rows.fold<double>(0, (sum, v) => sum + v.amount),
        'currency': 'TZS',
      },
    };
  }

  Map<String, dynamic> _create(Map<String, dynamic> body) {
    final type = _types.firstWhere(
      (t) => t.id == int.tryParse('${body['voucher_type_id']}'),
      orElse: () => _types.first,
    );
    final id = _nextVoucherId++;
    final voucher = MockVoucher(
      id: id,
      companyId: _current!.companyId ?? 1,
      number: _takeNumber(type),
      kind: body['kind'] == 'cash' ? 'cash' : 'bank',
      voucherTypeId: type.id,
      departmentId:
          int.tryParse('${body['department_id']}') ?? _current!.departmentId,
      requesterId: _current!.id,
      payee: '${body['payee'] ?? ''}',
      purpose: '${body['purpose'] ?? ''}',
      description: body['description'] as String?,
      amount: double.tryParse('${body['amount'] ?? 0}') ?? 0,
      paymentMethod: body['payment_method'] as String?,
      category: body['category'] as String?,
      accountRef: body['account_ref'] as String?,
      voucherDate:
          '${body['voucher_date'] ?? DateTime.now().toIso8601String().substring(0, 10)}',
      status: 'draft',
      currentStepPosition: null,
      createdAt: DateTime.now().toIso8601String(),
      notesToApprover: body['notes_to_approver'] as String?,
    )
      ..payeeBank = body['payee_bank'] as String?
      ..payeeAccountName = body['payee_account_name'] as String?
      ..payeeAccountNumber = body['payee_account_number'] as String?
      ..payeeBankBranch = body['payee_bank_branch'] as String?
      ..cashFloat = body['cash_float'] as String?;
    _vouchers.insert(0, voucher);
    _log(voucher, 'created', null);

    if (body['submit'] == true) _act(voucher, 'submit', const {});
    return {'data': _voucherJson(voucher, detailed: true)};
  }

  Map<String, dynamic> _update(MockVoucher v, Map<String, dynamic> body) {
    if (!_actions(v)['edit']!) {
      throw ApiException(403, 'This voucher can no longer be edited.');
    }
    v.payee = '${body['payee'] ?? v.payee}';
    v.purpose = '${body['purpose'] ?? v.purpose}';
    v.description = body['description'] as String? ?? v.description;
    v.amount = double.tryParse('${body['amount'] ?? v.amount}') ?? v.amount;
    v.paymentMethod = body['payment_method'] as String? ?? v.paymentMethod;
    v.accountRef = body['account_ref'] as String? ?? v.accountRef;
    v.category = body['category'] as String? ?? v.category;
    if (body['kind'] != null) v.kind = '${body['kind']}';
    if (body['department_id'] != null) {
      v.departmentId = int.tryParse('${body['department_id']}');
    }
    return {'data': _voucherJson(v, detailed: true)};
  }

  Map<String, dynamic> _act(
    MockVoucher v,
    String action,
    Map<String, dynamic> body,
  ) {
    final actions = _actions(v);
    final step = _stepAt(v.currentStepPosition);
    final comment = body['comment'] as String?;
    final now = DateTime.now().toIso8601String();

    switch (action) {
      case 'submit':
        if (!actions['submit']!) {
          throw ApiException(422, 'This voucher has already been submitted.');
        }
        final first = _applicable(v).where((s) => s.position != 1).firstOrNull;
        _log(
          v,
          v.status == 'changes_requested' ? 'resubmitted' : 'submitted',
          _applicable(v).first,
          comment: comment,
        );
        v.submittedAt ??= now;
        if (first == null) {
          v.status = 'paid';
          v.currentStepPosition = null;
        } else {
          v.status = 'in_review';
          v.currentStepPosition = first.position;
          v.stepSignedAt = null;
          _notifyAssignees(v, first);
        }

      case 'sign':
        if (!actions['sign']!) {
          throw ApiException(422, 'That action is not available at this step.');
        }
        final signature = body['use_saved_signature'] == true
            ? _current!.signature
            : (body['signature'] as String? ?? _current!.signature);
        if (signature == null) {
          throw ApiException(422, 'A signature is required.');
        }
        if (body['save_signature'] == true && body['signature'] != null) {
          _current!.signature = '${body['signature']}';
        }
        _log(v, 'signed', step, comment: comment, signature: signature);
        v.stepSignedAt = now;
        _notify(
          v.requesterId,
          title: '${v.number} signed by ${_current!.name}',
          titleSw: '${v.number} imesainiwa na ${_current!.name}',
          icon: 'signature',
          body: '${step?.name ?? 'This step'} complete.',
          voucherId: v.id,
        );

      case 'submit-signed':
        if (!actions['submit_signed']!) {
          throw ApiException(422, 'Sign the voucher before submitting it on.');
        }
        _log(v, 'forwarded', step, comment: comment);
        _advance(v, step!.position);

      case 'approve':
        if (!actions['approve']!) {
          throw ApiException(422, 'This step signs only; it cannot approve.');
        }
        if (step!.canSign && v.stepSignedAt == null) {
          final signature = body['signature'] as String? ?? _current!.signature;
          if (signature != null) {
            _log(v, 'signed', step, signature: signature);
            v.stepSignedAt = now;
          }
        }
        _log(v, 'approved', step, comment: comment);
        v.approvedAt = now;
        _advance(v, step.position);
        _notify(
          v.requesterId,
          title: '${v.number} approved',
          titleSw: '${v.number} imeidhinishwa',
          icon: 'seal',
          body: 'Cleared for payment — the cashier will release the funds.',
          voucherId: v.id,
        );

      case 'reject':
        if (!actions['reject']!) {
          throw ApiException(422, 'This step may not reject.');
        }
        if (comment == null || comment.trim().length < 3) {
          throw ApiException(422, 'A reason is required.', {
            'comment': ['A reason is required.'],
          });
        }
        _log(v, 'rejected', step, comment: comment);
        v.status = 'rejected';
        v.rejectedAt = now;
        v.currentStepPosition = null;
        _notify(
          v.requesterId,
          title: '${v.number} was rejected',
          titleSw: '${v.number} imekataliwa',
          icon: 'x',
          body: '${_current!.name}: $comment',
          voucherId: v.id,
        );

      case 'request-changes':
        if (!actions['request_changes']!) {
          throw ApiException(422, 'This step may not request changes.');
        }
        if (comment == null || comment.trim().length < 3) {
          throw ApiException(422, 'Say what needs to change.', {
            'comment': ['Say what needs to change.'],
          });
        }
        _log(v, 'changes_requested', step, comment: comment);
        v.status = 'changes_requested';
        v.currentStepPosition = null;
        v.stepSignedAt = null;
        _notify(
          v.requesterId,
          title: '${v.number} needs changes',
          titleSw: '${v.number} inahitaji mabadiliko',
          icon: 'undo',
          body: '${_current!.name}: $comment',
          voucherId: v.id,
        );

      case 'pay':
        if (!actions['pay']!) {
          throw ApiException(422, 'This voucher is not cleared for payment.');
        }
        final reference = '${body['reference'] ?? ''}'.trim();
        if (reference.isEmpty) {
          throw ApiException(422, 'A payment reference is required.', {
            'reference': ['A payment reference is required.'],
          });
        }
        _log(
          v,
          'paid',
          step,
          comment:
              comment ??
              'Funds released and reference recorded against the voucher.',
        );
        v.status = 'paid';
        v.paidAt = now;
        v.paymentReference = reference;
        v.paidBy = _current!.name;
        v.currentStepPosition = null;
        if (body['method'] != null) v.paymentMethod = '${body['method']}';
        _notify(
          v.requesterId,
          title: '${v.number} has been paid',
          titleSw: '${v.number} imelipwa',
          icon: 'check',
          body: '${_current!.name} released ${_money(v.amount)} · $reference.',
          voucherId: v.id,
        );

      case 'cancel':
        _log(v, 'cancelled', step, comment: comment);
        v.status = 'cancelled';
        v.currentStepPosition = null;

      case 'comments':
        final text = '${body['body'] ?? ''}'.trim();
        if (text.isEmpty) throw ApiException(422, 'Write something first.');
        v.comments.add(MockComment(_nextCommentId++, _current!.id, text, now));

      default:
        throw ApiException(404, 'Unknown action "$action".');
    }

    return {'data': _voucherJson(v, detailed: true)};
  }

  void _advance(MockVoucher v, int fromPosition) {
    final next = _applicable(
      v,
    ).where((s) => s.position > fromPosition).firstOrNull;

    if (next == null) {
      v.status = 'paid';
      v.paidAt ??= DateTime.now().toIso8601String();
      v.currentStepPosition = null;
      v.stepSignedAt = null;
      return;
    }

    v.currentStepPosition = next.position;
    v.stepSignedAt = null;
    // A payment step is only reached once the voucher has been approved.
    v.status = next.canPay && !next.canApprove ? 'approved' : 'in_review';
    _notifyAssignees(v, next);
  }

  /* ═════════════════════════════════════════════════════════ workflow ══ */

  List<MockStep> _applicable(MockVoucher v) => _steps
      .where(
        (s) =>
            (s.minAmount == null || v.amount >= s.minAmount!) &&
            (s.maxAmount == null || v.amount <= s.maxAmount!),
      )
      .toList();

  MockStep? _stepAt(int? position) => position == null
      ? null
      : _steps.where((s) => s.position == position).firstOrNull;

  List<MockUser> _assignees(MockVoucher v, MockStep step) {
    if (step.assignedUserId != null) {
      final u = _user(step.assignedUserId!);
      return u == null ? [] : [u];
    }
    final dept = _departments.where((d) => d.id == v.departmentId).firstOrNull;

    if (step.role == 'employee') {
      final u = _user(v.requesterId);
      return u == null ? [] : [u];
    }
    if (step.role == 'hod' && dept?.hodUserId != null) {
      final u = _user(dept!.hodUserId!);
      if (u != null) return [u];
    }
    if (step.role == 'ceo' && dept?.managerUserId != null) {
      final u = _user(dept!.managerUserId!);
      if (u != null) return [u];
    }
    return _users
        .where((u) => u.companyId == v.companyId && u.role == step.role)
        .toList();
  }

  bool _canActOn(MockVoucher v, MockStep? step) {
    if (step == null || _current == null) return false;
    if (_current!.role == 'company_admin') return true;
    return _assignees(v, step).any((u) => u.id == _current!.id);
  }

  Map<String, bool> _actions(MockVoucher v) {
    final me = _current!;
    final mine = v.requesterId == me.id;
    final step = _stepAt(v.currentStepPosition);
    final open = v.status == 'in_review' || v.status == 'approved';
    final canAct = open && _canActOn(v, step);
    final signedHere = v.stepSignedAt != null;

    final a = {
      'edit': false,
      'delete': false,
      'submit': false,
      'sign': false,
      'submit_signed': false,
      'approve': false,
      'reject': false,
      'request_changes': false,
      'cancel': false,
      'pay': false,
      'print': true,
      'download': true,
    };

    if (mine && (v.status == 'draft' || v.status == 'changes_requested')) {
      a['edit'] = true;
      a['submit'] = true;
      a['delete'] = v.status == 'draft';
    }
    if (mine && v.status == 'in_review') a['cancel'] = true;

    if (canAct && step != null) {
      if (step.canSign && !signedHere) a['sign'] = true;
      if (step.canSign && signedHere) a['submit_signed'] = true;
      if (step.canApprove) a['approve'] = v.status == 'in_review';
      if (step.canReject) a['reject'] = v.status == 'in_review';
      if (step.canRequestChanges) {
        a['request_changes'] = v.status == 'in_review';
      }
      if (step.canPay && v.status == 'approved') a['pay'] = true;
      a['print'] = step.canPrint;
      a['download'] = step.canPrint;
    }
    return a;
  }

  /// Vouchers this caller is permitted to see. An employee sees only their own.
  Iterable<MockVoucher> _visible() {
    final me = _current!;
    final mine = _vouchers.where((v) => v.companyId == me.companyId);

    if (me.role == 'employee') {
      return mine.where((v) => v.requesterId == me.id);
    }
    if (me.role == 'cashier') {
      return mine.where((v) => v.status == 'approved' || v.status == 'paid');
    }
    if (me.role == 'company_admin') return mine;

    // An approver sees their own vouchers, their departments' vouchers, and
    // anything that has reached or passed a step they act on.
    final scoped = _departments
        .where((d) => d.hodUserId == me.id || d.managerUserId == me.id)
        .map((d) => d.id)
        .toSet();

    return mine.where(
      (v) =>
          v.requesterId == me.id ||
          scoped.contains(v.departmentId) ||
          _approvals.any((e) => e.voucherId == v.id && e.actorId == me.id) ||
          _canActOn(v, _stepAt(v.currentStepPosition)),
    );
  }

  List<MockVoucher> _pending() => _visible()
      .where(
        (v) =>
            (v.status == 'in_review' || v.status == 'approved') &&
            _canActOn(v, _stepAt(v.currentStepPosition)),
      )
      .toList();

  /// How long a voucher has sat on its current step, in days.
  int _idleDays(MockVoucher v) {
    final events = _approvals.where((a) => a.voucherId == v.id).toList();
    final since = events.isEmpty
        ? (v.submittedAt ?? v.createdAt)
        : events.last.actedAt;
    return DateTime.now().difference(DateTime.parse(since)).inDays;
  }

  /// Open vouchers that have not moved in a while — the administrator's queue.
  List<MockVoucher> _stalled([int thresholdDays = 3]) {
    final rows = _visible()
        .where((v) =>
            (v.status == 'in_review' || v.status == 'approved') &&
            _idleDays(v) >= thresholdDays)
        .toList();
    rows.sort((a, b) => _idleDays(b).compareTo(_idleDays(a)));
    return rows;
  }

  /// Everything still moving through the route.
  List<MockVoucher> _inFlight() => _visible()
      .where((v) => v.status == 'in_review' || v.status == 'approved')
      .toList();

  /// What this user must personally do next.
  ///
  /// A dashboard is a queue of work, not a record of it. A voucher belongs
  /// here only while this user is holding it up; the moment they act it moves
  /// to whoever is next and leaves the list. History lives in Reports.
  List<MockVoucher> _actionQueue() {
    final me = _current!;

    if (me.role == 'employee') {
      final mine = _vouchers
          .where((v) =>
              v.companyId == me.companyId &&
              v.requesterId == me.id &&
              (v.status == 'draft' || v.status == 'changes_requested'))
          .toList();
      mine.sort((a, b) => b.voucherDate.compareTo(a.voucherDate));
      return mine;
    }

    if (me.role == 'company_admin') return _stalled();

    final queue = _pending();
    final mine = _vouchers.where((v) =>
        v.companyId == me.companyId &&
        v.requesterId == me.id &&
        (v.status == 'draft' || v.status == 'changes_requested'));

    return [
      ...queue,
      ...mine.where((m) => !queue.any((q) => q.id == m.id)),
    ];
  }

  /* ═══════════════════════════════════════════════════ presentation ══ */

  MockUser? _user(int id) => _users.where((u) => u.id == id).firstOrNull;

  static String _money(double amount, [String currency = 'TZS']) {
    final whole = amount.round().toString();
    final grouped = whole.replaceAllMapped(
      RegExp(r'(\d)(?=(\d{3})+$)'),
      (m) => '${m[1]},',
    );
    return '$currency $grouped';
  }

  static String _compact(double n) {
    if (n >= 1e9) return 'TZS ${(n / 1e9).toStringAsFixed(1)}B';
    if (n >= 1e6) return 'TZS ${(n / 1e6).toStringAsFixed(1)}M';
    if (n >= 1e3) return 'TZS ${(n / 1e3).round()}K';
    return _money(n);
  }

  static String _initials(String name) => name
      .trim()
      .split(RegExp(r'\s+'))
      .take(2)
      .map((w) => w.isEmpty ? '' : w[0].toUpperCase())
      .join();

  static const _roleLabels = {
    'employee': 'Employee',
    'hod': 'Head of Department',
    'ceo': 'CEO',
    'cashier': 'Cashier',
    'finance': 'Finance',
    'director': 'Director',
    'company_admin': 'Company Administrator',
    'super_admin': 'Platform Super Admin',
  };

  Map<String, dynamic> _userJson(MockUser u) => {
    'id': u.id,
    'company_id': u.companyId,
    'name': u.name,
    'initials': _initials(u.name),
    'email': u.email,
    'phone': null,
    'role': u.role,
    'role_label': _roleLabels[u.role] ?? u.role,
    'job_title': u.jobTitle,
    'employee_code': u.employeeCode,
    'status': u.status,
    'locale': u.locale,
    'theme': u.theme,
    'department_id': u.departmentId,
    'department': u.departmentId == null
        ? null
        : {
            'id': u.departmentId,
            'name':
                _departments
                    .where((d) => d.id == u.departmentId)
                    .firstOrNull
                    ?.name ??
                '',
          },
    'avatar_url': null,
    'has_signature': u.signature != null,
  };

  ({String key, String label, String labelSw, String tag}) _status(
    MockVoucher v,
  ) {
    switch (v.status) {
      case 'draft':
        return (
          key: 'draft',
          label: 'Draft',
          labelSw: 'Rasimu',
          tag: 'tag-neutral',
        );
      case 'rejected':
        return (
          key: 'rejected',
          label: 'Rejected',
          labelSw: 'Imekataliwa',
          tag: 'tag-accent-2',
        );
      case 'changes_requested':
        return (
          key: 'changes',
          label: 'Changes requested',
          labelSw: 'Mabadiliko yameombwa',
          tag: 'tag-accent-2',
        );
      case 'cancelled':
        return (
          key: 'cancelled',
          label: 'Cancelled',
          labelSw: 'Imeghairiwa',
          tag: 'tag-neutral',
        );
      case 'approved':
        return (
          key: 'awaiting_payment',
          label: 'Approved — awaiting payment',
          labelSw: 'Imeidhinishwa — inasubiri malipo',
          tag: 'tag-info',
        );
      case 'paid':
        return (
          key: 'paid',
          label: 'Paid & completed',
          labelSw: 'Imelipwa na kukamilika',
          tag: 'tag-accent',
        );
      default:
        final step = _stepAt(v.currentStepPosition);
        if (step == null) {
          return (
            key: 'in_review',
            label: 'In review',
            labelSw: 'Inapitiwa',
            tag: 'tag-outline',
          );
        }
        if (step.canSign && v.stepSignedAt != null) {
          return (
            key: 'signed',
            label: 'Signed — ready to submit',
            labelSw: 'Imesainiwa — tayari kutumwa',
            tag: 'tag-outline',
          );
        }
        if (step.canPay) {
          return (
            key: 'awaiting_payment',
            label: 'Awaiting payment',
            labelSw: 'Inasubiri malipo',
            tag: 'tag-info',
          );
        }
        if (step.canApprove) {
          return (
            key: 'pending_approval',
            label: 'Awaiting CEO approval',
            labelSw: 'Inasubiri idhini ya mkurugenzi',
            tag: 'tag-outline',
          );
        }
        return (
          key: 'pending_signature',
          label: 'Awaiting HOD signature',
          labelSw: 'Inasubiri sahihi ya mkuu wa idara',
          tag: 'tag-outline',
        );
    }
  }

  String _capabilityText(MockStep s) {
    final on = <String>[
      if (s.canSign) 'Sign',
      if (s.canApprove) 'Approve',
      if (s.canReject) 'Reject',
      if (s.canRequestChanges) 'Request changes',
      if (s.canPay) 'Record payment',
      if (s.canPrint) 'Print / PDF',
    ];
    return on.isEmpty ? 'View only' : on.join(' · ');
  }

  Map<String, dynamic> _voucherJson(MockVoucher v, {bool detailed = false}) {
    final status = _status(v);
    final step = _stepAt(v.currentStepPosition);
    final requester = _user(v.requesterId);
    final dept = _departments.where((d) => d.id == v.departmentId).firstOrNull;
    final type = _types.where((t) => t.id == v.voucherTypeId).firstOrNull;
    final sw = _current?.locale == 'sw';

    return {
      'id': v.id,
      'number': v.number,
      'kind': v.kind,
      'status': v.status,
      'status_key': status.key,
      'status_label': sw ? status.labelSw : status.label,
      'status_tag': status.tag,
      'payee': v.payee,
      'purpose': v.purpose,
      'description': v.description,
      'amount': v.amount,
      'currency': v.currency,
      'amount_text': _money(v.amount, v.currency),
      'amount_in_words': _words(v.amount),
      'payment_method': v.paymentMethod,
      'account_ref': v.accountRef,
      'category': v.category,
      'cost_centre': dept?.costCentre,
      'voucher_date': v.voucherDate,
      'verification_code': v.verificationCode,
      'voucher_type_id': v.voucherTypeId,
      'voucher_type': type == null
          ? null
          : {
              'id': type.id,
              'name': type.name,
              'label': sw ? type.nameSw : type.name,
            },
      'department_id': v.departmentId,
      'department': dept == null ? null : {'id': dept.id, 'name': dept.name},
      'requester_id': v.requesterId,
      'requester': requester == null
          ? null
          : {
              'id': requester.id,
              'name': requester.name,
              'initials': _initials(requester.name),
              'job_title': requester.jobTitle,
            },
      'current_step_position': v.currentStepPosition,
      'current_step': step == null
          ? null
          : {
              'id': step.position,
              'position': step.position,
              'name': step.name,
              'role': step.role,
              'capabilities': step.capabilities,
            },
      'is_signed_at_current_step': v.stepSignedAt != null,
      'is_editable': _actions(v)['edit'],
      'is_terminal': const ['paid', 'rejected', 'cancelled'].contains(v.status),
      'submitted_at': v.submittedAt,
      'approved_at': v.approvedAt,
      'rejected_at': v.rejectedAt,
      'paid_at': v.paidAt,
      'payment_reference': v.paymentReference,
      'paid_by': v.paidBy,
      'payee_bank': v.payeeBank,
      'payee_account_name': v.payeeAccountName,
      'payee_account_number': v.payeeAccountNumber,
      'payee_bank_branch': v.payeeBankBranch,
      'cheque_number': v.chequeNumber,
      'cash_float': v.cashFloat,
      'received_by': v.receivedBy,
      'created_at': v.createdAt,
      'attachments_count': v.attachments.length,
      'comments_count': v.comments.length,
      'actions': _actions(v),
      if (detailed) 'timeline': _timeline(v),
      if (detailed)
        'attachments': [
          for (var i = 0; i < v.attachments.length; i++)
            {
              'id': i + 1,
              'name': v.attachments[i],
              'size': '${180 + i * 46} KB',
              'is_image': v.attachments[i].endsWith('.jpg'),
            },
        ],
      if (detailed)
        'comments': v.comments.map((c) {
          final author = _user(c.userId);
          return {
            'id': c.id,
            'body': c.body,
            'created_at': c.createdAt,
            'user': {
              'id': c.userId,
              'name': author?.name ?? '—',
              'initials': _initials(author?.name ?? '—'),
              'role_label': _roleLabels[author?.role] ?? '',
            },
          };
        }).toList(),
    };
  }

  List<Map<String, dynamic>> _timeline(MockVoucher v) {
    final steps = _applicable(v);
    final trail = _approvals.where((a) => a.voucherId == v.id).toList();
    final paid = v.status == 'paid';
    final rejected = v.status == 'rejected';
    final current = v.currentStepPosition;

    final rows = <Map<String, dynamic>>[];

    for (final step in steps) {
      final events = trail
          .where((e) => e.stepPosition == step.position)
          .toList();
      final atThis = !paid && !rejected && current == step.position;
      final done =
          paid ||
          (current != null && step.position < current) ||
          (rejected &&
              events.any(
                (e) => const [
                  'approved',
                  'signed',
                  'forwarded',
                ].contains(e.action),
              ));

      MockApproval? last(String action) =>
          events.where((e) => e.action == action).lastOrNull;

      final rejectEvent = last('rejected');
      final changesEvent = last('changes_requested');
      final payEvent = last('paid');
      final approveEvent = last('approved');
      final signEvent = last('signed');
      final forwardEvent = last('forwarded');

      var act = 'Not started', actSw = 'Haijaanza';
      String? when, comment;

      if (step.position == 1) {
        if (v.status == 'draft') {
          act = 'Draft — not submitted';
          actSw = 'Rasimu — haijatumwa';
        } else {
          act = 'Created & submitted';
          actSw = 'Imetengenezwa na kutumwa';
          when = v.submittedAt;
          comment = v.attachments.isEmpty
              ? null
              : '${v.attachments.length} supporting document(s) attached.';
        }
      } else if (rejectEvent != null) {
        act = 'Rejected';
        actSw = 'Imekataliwa';
        when = rejectEvent.actedAt;
        comment = rejectEvent.comment;
      } else if (changesEvent != null) {
        act = 'Changes requested';
        actSw = 'Mabadiliko yameombwa';
        when = changesEvent.actedAt;
        comment = changesEvent.comment;
      } else if (payEvent != null) {
        act = 'Paid';
        actSw = 'Imelipwa';
        when = payEvent.actedAt;
        comment = payEvent.comment;
      } else if (approveEvent != null) {
        act = 'Approved';
        actSw = 'Imeidhinishwa';
        when = approveEvent.actedAt;
        comment = approveEvent.comment ?? 'Cleared for payment.';
      } else if (signEvent != null && forwardEvent != null) {
        act = 'Reviewed & signed';
        actSw = 'Imepitiwa na kusainiwa';
        when = signEvent.actedAt;
        comment = 'Signature applied and forwarded to the next step.';
      } else if (signEvent != null && atThis) {
        act = 'Signed — not yet submitted onward';
        actSw = 'Imesainiwa — haijatumwa mbele';
        when = signEvent.actedAt;
        comment = 'This step signs only; it makes no approval decision.';
      } else if (atThis) {
        if (step.canPay) {
          act = 'Awaiting payment';
          actSw = 'Inasubiri malipo';
        } else if (step.canApprove) {
          act = 'Awaiting approval';
          actSw = 'Inasubiri idhini';
        } else {
          act = 'Awaiting signature';
          actSw = 'Inasubiri sahihi';
        }
      }

      final bad = rejectEvent != null || changesEvent != null;
      final good = done && !bad;
      final actor = events.isEmpty ? null : _user(events.last.actorId);
      final assignee = _assignees(v, step).firstOrNull;

      rows.add({
        'position': step.position,
        'name': step.name,
        'name_sw': step.nameSw,
        'sub': 'Step ${step.position} · ${_roleLabels[step.role] ?? step.role}',
        'sub_sw':
            'Hatua ${step.position} · ${_roleLabels[step.role] ?? step.role}',
        'person': actor?.name ?? assignee?.name ?? step.assigneeHint,
        'person_title': actor?.jobTitle ?? assignee?.jobTitle ?? '',
        'act': act,
        'act_sw': actSw,
        'when': when,
        'comment': comment,
        'signature': signEvent?.signature,
        'capabilities': step.capabilities,
        'capability_text': _capabilityText(step),
        'state': bad
            ? 'rejected'
            : (good ? 'done' : (atThis ? 'current' : 'pending')),
        'icon': bad ? 'x' : (good ? 'check' : (atThis ? 'hourglass' : 'dash')),
      });
    }

    rows.add({
      'position': null,
      'name': 'Completed',
      'name_sw': 'Imekamilika',
      'sub': 'System',
      'sub_sw': 'Mfumo',
      'person': 'VouchFlow',
      'person_title': '',
      'act': paid
          ? 'Voucher completed'
          : (rejected ? 'Closed — rejected' : 'Not completed'),
      'act_sw': paid
          ? 'Vocha imekamilika'
          : (rejected ? 'Imefungwa — imekataliwa' : 'Haijakamilika'),
      'when': paid ? v.paidAt : (rejected ? v.rejectedAt : null),
      'comment': paid
          ? 'Approval ID ${v.verificationCode} · PDF ready with every captured mark.'
          : null,
      'signature': null,
      'capabilities': const {'print': true, 'download': true},
      'capability_text': 'Print · Download PDF · Share',
      'state': paid ? 'done' : (rejected ? 'rejected' : 'pending'),
      'icon': paid ? 'check' : 'dash',
    });

    return rows;
  }

  Map<String, dynamic> _notificationJson(MockNotification n) => {
    'id': n.id,
    'icon': n.icon,
    'title': _current?.locale == 'sw' ? n.titleSw : n.title,
    'body': _current?.locale == 'sw' ? n.bodySw : n.body,
    'entity_type': n.voucherId == null ? null : 'Voucher',
    'entity_id': n.voucherId,
    'is_unread': n.readAt == null,
    'created_at': n.createdAt,
  };

  /* ═════════════════════════════════════════════════════════ dashboard ══ */
  /// The dashboard payload.
  ///
  /// Every role gets the same thing: the work that is theirs to do right now,
  /// and a few counters for context. Nothing already dealt with appears here —
  /// once a user acts, the voucher moves on and drops off this screen.
  Map<String, dynamic> _dashboard() {
    final me = _current!;
    final hour = DateTime.now().hour;
    final greeting = hour < 12
        ? 'Good morning'
        : (hour < 17 ? 'Good afternoon' : 'Good evening');

    final visible = _visible().toList();
    final queue = _actionQueue();
    final open = _inFlight();

    Map<String, dynamic> stat(
      String label,
      String value,
      String sub, [
      String icon = 'chart',
      String? trend,
      bool? up,
    ]) => {
      'label': label, 'value': value, 'sub': sub,
      'icon': icon, 'trend': trend, 'up': up,
    };

    String plural(int n) => '$n ${n == 1 ? 'voucher' : 'vouchers'}';
    double total(Iterable<MockVoucher> rows) =>
        rows.fold<double>(0, (sum, v) => sum + v.amount);

    List<MockVoucher> paidThisMonth() {
      final from = DateTime(DateTime.now().year, DateTime.now().month);
      return visible
          .where((v) =>
              v.status == 'paid' &&
              v.paidAt != null &&
              DateTime.parse(v.paidAt!).isAfter(from))
          .toList();
    }

    final base = {
      'role': me.role,
      'greeting': greeting,
      'queue': queue.map((v) => _voucherJson(v)).toList(),
      'queue_total_text': _money(total(queue)),
    };

    if (me.role == 'cashier') {
      final cash = queue.where((v) => v.kind == 'cash').toList();
      final bank = queue.where((v) => v.kind == 'bank').toList();
      return {
        ...base,
        'data': {
          'headline': queue.isEmpty ? 'Nothing to pay' : '${plural(queue.length)} to pay',
          'sub': queue.isEmpty
              ? 'Every approved voucher has been released. New ones arrive the moment they are approved.'
              : 'Each one is approved and cleared for release. Paying it closes the voucher.',
          'stats': [
            stat('Awaiting release', '${queue.length}', _money(total(queue)), 'hourglass'),
            stat('Cash', _compact(total(cash)), '${plural(cash.length)} from a float', 'money'),
            stat('Bank transfers', _compact(total(bank)), '${plural(bank.length)} to an account', 'bank'),
            stat('Released this month', _compact(total(paidThisMonth())), '${paidThisMonth().length} settled', 'check'),
          ],
        },
      };
    }

    if (me.role == 'employee') {
      final withOthers = visible
          .where((v) => v.status == 'in_review' || v.status == 'approved')
          .toList();
      final settled = visible.where((v) => v.status == 'paid').toList();
      return {
        ...base,
        'data': {
          'headline': queue.isEmpty
              ? 'Nothing needs your attention'
              : '${plural(queue.length)} ${queue.length == 1 ? 'needs' : 'need'} your attention',
          'sub': queue.isEmpty
              ? '${withOthers.isEmpty ? 'You have nothing in the workflow.' : '${plural(withOthers.length)} with an approver.'} Your full history is in Reports.'
              : 'Finish these and they move on for review.',
          'stats': [
            stat('On you', '${queue.length}', 'drafts and returns', 'receipt'),
            stat('With an approver', '${withOthers.length}', _compact(total(withOthers)), 'hourglass'),
            stat('Paid', '${settled.length}', _compact(total(settled)), 'check'),
            stat('Raised this year', '${visible.length}', _compact(total(visible)), 'coins'),
          ],
        },
      };
    }

    if (me.role == 'company_admin') {
      final settled = paidThisMonth();
      return {
        ...base,
        'data': {
          'headline': queue.isEmpty
              ? 'The workflow is moving'
              : '${plural(queue.length)} ${queue.length == 1 ? 'has' : 'have'} stalled',
          'sub': queue.isEmpty
              ? '${plural(open.length)} in the workflow, none of them stuck. Company reporting is in Reports.'
              : 'These have not moved in three days or more.',
          'stats': [
            stat('Stalled', '${queue.length}', 'three days or more', 'undo'),
            stat('In the workflow', '${open.length}', _compact(total(open)), 'hourglass'),
            stat('Paid this month', '${settled.length}', _compact(total(settled)), 'check'),
            stat('People', '${_users.where((u) => u.companyId == me.companyId).length}',
                '${_departments.where((d) => d.companyId == me.companyId).length} departments', 'receipt'),
          ],
        },
      };
    }

    /* Approvers. Whether this person signs or decides is a property of the
       steps they hold, not of whatever is in the queue right now — otherwise
       the wording flips the moment they clear it. */
    final mySteps = _steps.where((s) =>
        s.assignedUserId == me.id ||
        (s.assignedUserId == null && s.role == me.role));
    final signOnly =
        mySteps.isNotEmpty && mySteps.every((s) => !s.canApprove);

    final acted = _approvals
        .where((a) =>
            a.actorId == me.id &&
            const ['signed', 'approved', 'paid'].contains(a.action))
        .length;
    final returned = _approvals
        .where((a) =>
            a.actorId == me.id &&
            const ['rejected', 'changes_requested'].contains(a.action))
        .length;

    return {
      ...base,
      'data': {
        'headline': queue.isEmpty
            ? 'Nothing awaiting your ${signOnly ? 'signature' : 'decision'}'
            : '${plural(queue.length)} awaiting your ${signOnly ? 'signature' : 'decision'}',
        'sub': queue.isEmpty
            ? 'Your work is clear. Past decisions are in Reports.'
            : (signOnly
                ? 'Your step signs and passes the voucher on — the approval decision belongs to a later step.'
                : 'Each one has reached your step. Acting on it moves it to whoever is next.'),
        'stats': [
          stat('Awaiting you', '${queue.length}', _money(total(queue)), 'hourglass'),
          stat('In the workflow', '${open.length}', _compact(total(open)), 'receipt'),
          stat('Actioned', '$acted', 'signed or approved', 'signature'),
          stat('Returned', '$returned', 'rejected or sent back', 'undo'),
        ],
      },
    };
  }

  /* ═══════════════════════════════════════════════════════════ helpers ══ */

  MockVoucher _find(int id) {
    final v = _vouchers.where((x) => x.id == id).firstOrNull;
    if (v == null) throw ApiException(404, 'Voucher not found.');
    if (!_visible().any((x) => x.id == id)) {
      throw ApiException(
        403,
        'This voucher belongs to another part of the business.',
      );
    }
    return v;
  }

  void _log(
    MockVoucher v,
    String action,
    MockStep? step, {
    String? comment,
    String? signature,
  }) {
    _approvals.add(
      MockApproval(
        id: _nextApprovalId++,
        voucherId: v.id,
        stepPosition: step?.position,
        actorId: _current!.id,
        actorName: _current!.name,
        action: action,
        actedAt: DateTime.now().toIso8601String(),
        comment: comment,
        signature: signature,
      ),
    );
  }

  void _notifyAssignees(MockVoucher v, MockStep step) {
    final verb = step.canPay
        ? 'payment'
        : (step.canApprove ? 'approval' : 'signature');
    for (final u in _assignees(v, step)) {
      _notify(
        u.id,
        title: '${v.number} needs your $verb',
        titleSw:
            '${v.number} inahitaji ${step.canPay ? 'malipo' : (step.canApprove ? 'idhini' : 'sahihi')} yako',
        icon: step.canPay ? 'wallet' : (step.canApprove ? 'seal' : 'signature'),
        body:
            '${_user(v.requesterId)?.name ?? ''} · ${_money(v.amount)} — ${v.purpose}',
        voucherId: v.id,
      );
    }
  }

  void _notify(
    int userId, {
    required String title,
    required String titleSw,
    required String icon,
    String? body,
    int? voucherId,
  }) {
    _notifications.insert(
      0,
      MockNotification(
        id: _nextNotificationId++,
        userId: userId,
        icon: icon,
        title: title,
        titleSw: titleSw,
        body: body,
        bodySw: body,
        createdAt: DateTime.now().toIso8601String(),
        voucherId: voucherId,
      ),
    );
  }

  String _previewNumber(MockVoucherType t) =>
      '${t.prefix}-${DateTime.now().year}-${t.nextNumber.toString().padLeft(6, '0')}';

  String _takeNumber(MockVoucherType t) {
    final value = _previewNumber(t);
    t.nextNumber += 1;
    return value;
  }

  static const _units = [
    '',
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'eleven',
    'twelve',
    'thirteen',
    'fourteen',
    'fifteen',
    'sixteen',
    'seventeen',
    'eighteen',
    'nineteen',
  ];
  static const _tens = [
    '',
    '',
    'twenty',
    'thirty',
    'forty',
    'fifty',
    'sixty',
    'seventy',
    'eighty',
    'ninety',
  ];

  static String _under1000(int n) {
    if (n < 20) return _units[n];
    if (n < 100) {
      return _tens[n ~/ 10] + (n % 10 != 0 ? '-${_units[n % 10]}' : '');
    }
    return '${_units[n ~/ 100]} hundred'
        '${n % 100 != 0 ? ' ${_under1000(n % 100)}' : ''}';
  }

  static String _words(double amount) {
    var rest = amount.round().abs();
    if (rest == 0) return 'Zero shillings only';
    final parts = <String>[];
    for (final pair in const [
      [1000000000, 'billion'],
      [1000000, 'million'],
      [1000, 'thousand'],
    ]) {
      final value = pair[0] as int;
      if (rest >= value) {
        parts.add('${_under1000(rest ~/ value)} ${pair[1]}');
        rest %= value;
      }
    }
    if (rest > 0) parts.add(_under1000(rest));
    final text = parts.join(' ');
    return '${text[0].toUpperCase()}${text.substring(1)} shillings only';
  }

  /* ══════════════════════════════════════════════════════════════ seed ══ */

  void _seed() {
    _departments.addAll(const [
      MockDepartment(1, 1, 'Finance', 'CC-FIN', 4, 5),
      MockDepartment(2, 1, 'Procurement', 'CC-PRO', 9, 5),
      MockDepartment(3, 1, 'Production', 'CC-PRD', 9, 5),
      MockDepartment(4, 1, 'Transport & Logistics', 'CC-TRN', 12, 5),
      MockDepartment(5, 1, 'Human Resources', 'CC-HR', 13, 5),
      MockDepartment(6, 1, 'Sales & Distribution', 'CC-SLS', 12, 5),
      MockDepartment(7, 1, 'Quality Assurance', 'CC-QA', 4, 5),
    ]);

    _users.addAll([
      MockUser(id: 2, companyId: 1, name: 'Neema Shirima', email: 'admin@watercom.test', role: 'company_admin', jobTitle: 'Company Administrator', employeeCode: 'WC-0087', departmentId: 5),
      MockUser(id: 3, companyId: 1, name: 'Frank Kessy', email: 'frank@watercom.test', role: 'employee', jobTitle: 'Procurement Officer', employeeCode: 'WC-0114', departmentId: 2),
      MockUser(id: 4, companyId: 1, name: 'Rehema Kilonzo', email: 'rehema@watercom.test', role: 'hod', jobTitle: 'Head of Finance', employeeCode: 'WC-0032', departmentId: 1, signature: sampleSignature),
      MockUser(id: 5, companyId: 1, name: 'Emmanuel Massawe', email: 'emmanuel@watercom.test', role: 'ceo', jobTitle: 'Managing Director', employeeCode: 'WC-0008', departmentId: 1, signature: sampleSignature),
      MockUser(id: 6, companyId: 1, name: 'Mwajuma Hamisi', email: 'mwajuma@watercom.test', role: 'cashier', jobTitle: 'Cashier · Finance', employeeCode: 'WC-0056', departmentId: 1, signature: sampleSignature),
      MockUser(id: 7, companyId: 1, name: 'Baraka Ndosi', email: 'baraka@watercom.test', role: 'employee', jobTitle: 'Transport Supervisor', employeeCode: 'WC-0129', departmentId: 4),
      MockUser(id: 8, companyId: 1, name: 'Gloria Mtei', email: 'gloria@watercom.test', role: 'employee', jobTitle: 'Quality Assurance Officer', employeeCode: 'WC-0141', departmentId: 7),
      MockUser(id: 9, companyId: 1, name: 'Joseph Mrisho', email: 'joseph@watercom.test', role: 'hod', jobTitle: 'Head of Procurement', employeeCode: 'WC-0021', departmentId: 2, signature: sampleSignature),
      MockUser(id: 12, companyId: 1, name: 'Salum Bakari', email: 'salum@watercom.test', role: 'hod', jobTitle: 'Transport Manager', employeeCode: 'WC-0044', departmentId: 4, signature: sampleSignature),
      MockUser(id: 13, companyId: 1, name: 'Anna Lyimo', email: 'anna@watercom.test', role: 'hod', jobTitle: 'Head of Human Resources', employeeCode: 'WC-0061', departmentId: 5, signature: sampleSignature),
      MockUser(id: 14, companyId: 1, name: 'Doreen Massawe', email: 'doreen@watercom.test', role: 'employee', jobTitle: 'Human Resources Officer', employeeCode: 'WC-0152', departmentId: 5),
    ]);

    _types.addAll([
      MockVoucherType(101, 1, 'Payment Voucher', 'Vocha ya malipo', 'PV', 1246),
      MockVoucherType(
        102,
        1,
        'Petty Cash Voucher',
        'Vocha ya fedha taslimu',
        'PC',
        319,
      ),
      MockVoucherType(103, 1, 'Expense Voucher', 'Vocha ya matumizi', 'EX', 88),
      MockVoucherType(
        104,
        1,
        'Advance Voucher',
        'Vocha ya malipo ya awali',
        'AD',
        43,
      ),
    ]);

    /* Live work, positioned so every persona opens the prototype with a real
       queue in front of them and an empty one the moment they clear it. */

    // ── awaiting the Procurement head ──
    _addVoucher(
      number: 'PV-2026-001248', kind: 'bank', typeId: 101, dept: 2, requester: 3,
      payee: 'Kibo Preforms Limited', purpose: 'PET preforms — Afiya 500 ml line',
      description: '420,000 × 24.5 g preforms for the Afiya still-water line, against framework contract WC/PR/2026/04.',
      amount: 18400000, method: 'Bank Transfer', category: 'Raw materials',
      ref: 'INV-KP-88213', daysAgo: 2, status: 'in_review', step: 2,
      bank: 'NMB Bank', accountName: 'Kibo Preforms Limited',
      accountNumber: '40910022317', bankBranch: 'Ubungo Branch',
      attachments: ['invoice-KP-88213.pdf', 'goods-received-note.jpg'],
      trail: [
        ('created', 3, null, 2, 7, null, false),
        ('submitted', 3, 1, 2, 8, null, false),
      ],
    );

    // ── signed by the Transport head, still to be sent onward ──
    _addVoucher(
      number: 'PV-2026-001247', kind: 'bank', typeId: 101, dept: 4, requester: 7,
      payee: 'Coastal Transporters Limited',
      purpose: 'Distribution haulage — Mwanza and Mbeya routes',
      description: 'Outbound haulage of 38 pallets of finished goods to the Mwanza and Mbeya depots, week 36.',
      amount: 6750000, method: 'Bank Transfer', category: 'Distribution',
      ref: 'INV-CT-4471', daysAgo: 3, status: 'in_review', step: 2, signedAtStep: true,
      bank: 'CRDB Bank', accountName: 'Coastal Transporters Ltd',
      accountNumber: '0152447199031', bankBranch: 'Nyerere Road Branch',
      attachments: ['delivery-schedule.pdf'],
      trail: [
        ('created', 7, null, 3, 7, null, false),
        ('submitted', 7, 1, 3, 8, null, false),
        ('signed', 12, 2, 2, 9, 'Rates match the 2026 haulage schedule.', true),
      ],
    );

    // ── awaiting the HR head ──
    _addVoucher(
      number: 'PC-2026-000324', kind: 'cash', typeId: 102, dept: 5, requester: 14,
      payee: 'Bahati Catering Services', purpose: 'Staff canteen supplies — September',
      description: 'Monthly canteen provisions for the Kibada plant, 240 staff meals per week.',
      amount: 940000, method: 'Cash', category: 'Staff welfare', ref: 'RCP-1180',
      float: 'Kibada plant petty cash float',
      daysAgo: 1, status: 'in_review', step: 2,
      trail: [
        ('created', 14, null, 1, 8, null, false),
        ('submitted', 14, 1, 1, 9, null, false),
      ],
    );

    // ── awaiting the Managing Director ──
    _addVoucher(
      number: 'PV-2026-001245', kind: 'bank', typeId: 101, dept: 3, requester: 3,
      payee: 'BOC Tanzania Limited', purpose: 'Food-grade CO₂ — Supa Cola line',
      description: 'Twelve tonnes of beverage-grade carbon dioxide for the Supa Cola carbonation plant.',
      amount: 9200000, method: 'Bank Transfer', category: 'Raw materials',
      ref: 'INV-BOC-2214', daysAgo: 5, status: 'in_review', step: 3,
      bank: 'Stanbic Bank', accountName: 'BOC Tanzania Limited',
      accountNumber: '9120044178', bankBranch: 'Mikocheni Branch',
      attachments: ['certificate-of-analysis.pdf'],
      trail: [
        ('created', 3, null, 5, 7, null, false),
        ('submitted', 3, 1, 5, 8, null, false),
        ('signed', 9, 2, 4, 9, null, true),
        ('forwarded', 9, 2, 4, 10, 'Checked against the October production plan.', false),
      ],
    );
    _addVoucher(
      number: 'PV-2026-001244', kind: 'bank', typeId: 101, dept: 1, requester: 3,
      payee: 'TANESCO', purpose: 'Kibada plant electricity — August',
      description: 'Industrial supply for the Kibada bottling plant, meter 41-882-0173.',
      amount: 14850000, method: 'Bank Transfer', category: 'Utilities',
      ref: 'BILL-4188-08', daysAgo: 6, status: 'in_review', step: 3,
      bank: 'CRDB Bank', accountName: 'Tanzania Electric Supply Co Ltd',
      accountNumber: '0150310099200', bankBranch: 'Azikiwe Branch',
      trail: [
        ('created', 3, null, 6, 7, null, false),
        ('submitted', 3, 1, 6, 8, null, false),
        ('signed', 4, 2, 5, 9, null, true),
        ('forwarded', 4, 2, 5, 10, null, false),
      ],
    );
    _addVoucher(
      number: 'PC-2026-000322', kind: 'cash', typeId: 102, dept: 7, requester: 8,
      payee: 'Afri-Chem Supplies', purpose: 'Laboratory reagents — water testing',
      description: 'Microbiological media and reagents for routine potable-water testing.',
      amount: 1320000, method: 'Cash', category: 'Quality control', ref: 'QT-7741',
      float: 'Laboratory petty cash float',
      daysAgo: 4, status: 'in_review', step: 3,
      trail: [
        ('created', 8, null, 4, 8, null, false),
        ('submitted', 8, 1, 4, 9, null, false),
        ('signed', 4, 2, 3, 11, null, true),
        ('forwarded', 4, 2, 3, 11, null, false),
      ],
    );

    // ── approved, waiting on the cashier ──
    _addVoucher(
      number: 'PV-2026-001240', kind: 'bank', typeId: 101, dept: 2, requester: 3,
      payee: 'Tanpack Labels Limited', purpose: 'Shrink labels — Afiya and Jembe',
      description: 'Roll-fed shrink sleeves for the Afiya 500 ml and Jembe Energy 300 ml lines.',
      amount: 7600000, method: 'Bank Transfer', category: 'Packaging',
      ref: 'INV-TP-6620', daysAgo: 8, status: 'approved', step: 4,
      bank: 'NMB Bank', accountName: 'Tanpack Labels Limited',
      accountNumber: '40120087755', bankBranch: "Chang'ombe Branch",
      attachments: ['artwork-approval.pdf'],
      trail: [
        ('created', 3, null, 8, 7, null, false),
        ('submitted', 3, 1, 8, 8, null, false),
        ('signed', 9, 2, 7, 9, null, true),
        ('forwarded', 9, 2, 7, 10, null, false),
        ('approved', 5, 3, 6, 15, 'Cleared for payment.', false),
      ],
    );
    _addVoucher(
      number: 'PC-2026-000318', kind: 'cash', typeId: 102, dept: 4, requester: 7,
      payee: 'Msasani Motor Spares', purpose: 'Tyres and spares — truck T 4471 DTX',
      description: 'Four drive tyres and a service kit for the Mbeya route truck.',
      amount: 2150000, method: 'Cash', category: 'Fleet maintenance', ref: 'RCP-3312',
      float: 'Transport petty cash float',
      daysAgo: 9, status: 'approved', step: 4,
      trail: [
        ('created', 7, null, 9, 7, null, false),
        ('submitted', 7, 1, 9, 8, null, false),
        ('signed', 12, 2, 8, 9, null, true),
        ('forwarded', 12, 2, 8, 10, null, false),
        ('approved', 5, 3, 7, 15, null, false),
      ],
    );
    _addVoucher(
      number: 'PV-2026-001239', kind: 'bank', typeId: 101, dept: 5, requester: 14,
      payee: 'National Social Security Fund',
      purpose: 'Statutory contributions — August 2026',
      description: 'Employer and employee NSSF contributions for 214 staff.',
      amount: 5480000, method: 'Bank Transfer', category: 'Statutory',
      ref: 'NSSF-08-2026', daysAgo: 10, status: 'approved', step: 4,
      bank: 'CRDB Bank', accountName: 'National Social Security Fund',
      accountNumber: '0150200011003', bankBranch: 'Tower Branch',
      trail: [
        ('created', 14, null, 10, 7, null, false),
        ('submitted', 14, 1, 10, 8, null, false),
        ('signed', 13, 2, 9, 9, null, true),
        ('forwarded', 13, 2, 9, 10, null, false),
        ('approved', 5, 3, 8, 15, null, false),
      ],
    );

    // ── closed ──
    _addVoucher(
      number: 'PV-2026-001236', kind: 'bank', typeId: 101, dept: 3, requester: 3,
      payee: 'Kilimanjaro Sugar Distributors', purpose: 'Refined sugar — 20 tonnes',
      description: 'Refined white sugar for the Supa Cola and Afiya juice lines.',
      amount: 22300000, method: 'Bank Transfer', category: 'Raw materials',
      ref: 'INV-KS-1180', daysAgo: 6, status: 'paid', step: null,
      bank: 'NBC Bank', accountName: 'Kilimanjaro Sugar Distributors',
      accountNumber: '011103004471', bankBranch: 'Moshi Branch',
      paymentRef: 'TRF-2026-884120', paidBy: 'Mwajuma Hamisi',
      trail: [
        ('created', 3, null, 6, 7, null, false),
        ('submitted', 3, 1, 6, 8, null, false),
        ('signed', 9, 2, 5, 9, null, true),
        ('forwarded', 9, 2, 5, 10, null, false),
        ('approved', 5, 3, 5, 15, null, false),
        ('paid', 6, 4, 4, 10, 'Funds released and reference recorded.', false),
      ],
    );
    _addVoucher(
      number: 'AD-2026-000042', kind: 'cash', typeId: 104, dept: 4, requester: 7,
      payee: 'Baraka Ndosi', purpose: 'Travel advance — Mbeya depot stock audit',
      description: 'Three nights, per diem and fuel for the quarterly stock count.',
      amount: 860000, method: 'Mobile Money', category: 'Travel', ref: 'ADV-0042',
      float: 'Transport petty cash float',
      daysAgo: 14, status: 'rejected', step: null,
      trail: [
        ('created', 7, null, 14, 7, null, false),
        ('submitted', 7, 1, 14, 8, null, false),
        ('signed', 12, 2, 13, 9, null, true),
        ('forwarded', 12, 2, 13, 10, null, false),
        ('rejected', 5, 3, 13, 14, 'The Mbeya depot holds its own float — draw the advance there.', false),
      ],
    );

    // ── back with the requester ──
    _addVoucher(
      number: 'EX-2026-000011', kind: 'bank', typeId: 103, dept: 2, requester: 3,
      payee: 'Sumaria Industries Limited', purpose: 'Closures and caps — August arrears',
      description: 'Outstanding balance on 1.2 million 28 mm closures delivered in August.',
      amount: 3150000, method: 'Bank Transfer', category: 'Packaging',
      ref: 'INV-SI-5590', daysAgo: 5, status: 'changes_requested', step: null,
      bank: 'Exim Bank', accountName: 'Sumaria Industries Ltd',
      accountNumber: '0100200455', bankBranch: 'Nyerere Road Branch',
      trail: [
        ('created', 3, null, 5, 7, null, false),
        ('submitted', 3, 1, 5, 8, null, false),
        ('changes_requested', 9, 2, 4, 11, 'Attach the August goods-received note and the reconciled supplier statement.', false),
      ],
    );
    _addVoucher(
      number: 'PV-2026-001249', kind: 'bank', typeId: 101, dept: 2, requester: 3,
      payee: 'Coastal Packaging Limited', purpose: 'Shrink film — October order',
      description: "Draft pending the supplier's confirmed quotation.",
      amount: 4100000, method: 'Bank Transfer', category: 'Packaging', ref: '',
      daysAgo: 0, status: 'draft', step: null,
      trail: [('created', 3, null, 0, 9, null, false)],
    );

    // Enough history for the charts and registers to look lived-in.
    const payees = [
      'Highland Freight Services',
      'Kariakoo Stationers',
      'Uhuru Internet Services',
      'Coastal Packaging Ltd',
    ];
    const purposes = [
      'Monthly courier retainer',
      'Warehouse cleaning contract',
      'Generator servicing',
      'Security guarding — monthly',
    ];
    const cast = [(3, 2, 9), (7, 5, 9), (3, 3, 4), (7, 4, 4)];

    for (var h = 1; h <= 18; h++) {
      final daysAgo = 20 + h * 6;
      final rejected = h % 9 == 0;
      final (requester, dept, hod) = cast[h % cast.length];
      _addVoucher(
        number: 'PV-2026-${(1100 + h).toString().padLeft(6, '0')}',
        kind: h % 3 == 0 ? 'cash' : 'bank',
        typeId: 101,
        dept: dept,
        requester: requester,
        payee: payees[h % payees.length],
        purpose: purposes[h % purposes.length],
        description:
            'Recurring operational cost, approved against the monthly budget.',
        amount: (2 + (h * 7) % 88) * 100000,
        method: h % 3 == 0 ? 'Cash' : 'Bank Transfer',
        category: const [
          'Logistics',
          'Premises',
          'Transport',
          'Utilities',
        ][h % 4],
        ref: 'INV-${20000 + h}',
        daysAgo: daysAgo,
        status: rejected ? 'rejected' : 'paid',
        step: null,
        paymentRef: rejected ? null : 'TRX-${700000 + h}',
        paidBy: rejected ? null : 'Mwajuma Hamisi',
        bank: h % 3 == 0 ? null : const ['CRDB Bank', 'NMB Bank', 'NBC Bank'][h % 3],
        accountName: h % 3 == 0 ? null : payees[h % payees.length],
        accountNumber: h % 3 == 0 ? null : '01${(500000 + h * 137).toString().padLeft(9, "0")}',
        bankBranch: h % 3 == 0 ? null : const ['Tower Branch', 'Ubungo Branch', 'Kariakoo Branch'][h % 3],
        float: h % 3 == 0 ? 'Kibada plant petty cash float' : null,
        receivedBy: h % 3 == 0 && !rejected ? payees[h % payees.length] : null,
        trail: [
          ('created', requester, null, daysAgo, 7, null, false),
          ('submitted', requester, 1, daysAgo, 8, null, false),
          ('signed', hod, 2, daysAgo - 1, 9, null, true),
          ('forwarded', hod, 2, daysAgo - 1, 10, null, false),
          if (rejected)
            (
              'rejected',
              5,
              3,
              daysAgo - 1,
              14,
              'Outside the approved budget for this period.',
              false,
            )
          else ...[
            ('approved', 5, 3, daysAgo - 1, 15, null, false),
            ('paid', 6, 4, daysAgo - 2, 10, null, false),
          ],
        ],
      );
    }

    _vouchers[0].comments.add(
      MockComment(
        _nextCommentId++,
        4,
        'Within the Q3 logistics budget. The rate matches the framework contract.',
        iso(2, 9, 20),
      ),
    );

    // Seed the inbox from what is actually waiting on each person.
    for (final v in _vouchers) {
      final step = _stepAt(v.currentStepPosition);
      if (step == null) continue;
      _notifyAssignees(v, step);
    }
  }

  void _addVoucher({
    required String number,
    required String kind,
    required int typeId,
    required int dept,
    required int requester,
    required String payee,
    required String purpose,
    required String description,
    required double amount,
    required String method,
    required String category,
    required String ref,
    required int daysAgo,
    required String status,
    required int? step,
    bool signedAtStep = false,
    String? paymentRef,
    String? paidBy,
    String? bank,
    String? accountName,
    String? accountNumber,
    String? bankBranch,
    String? float,
    String? receivedBy,
    List<String> attachments = const [],
    List<(String, int, int?, int, int, String?, bool)> trail = const [],
  }) {
    final id = _nextVoucherId++;
    final v = MockVoucher(
      id: id,
      companyId: 1,
      number: number,
      kind: kind,
      voucherTypeId: typeId,
      departmentId: dept,
      requesterId: requester,
      payee: payee,
      purpose: purpose,
      description: description,
      amount: amount,
      paymentMethod: method,
      category: category,
      accountRef: ref.isEmpty ? null : ref,
      voucherDate: iso(daysAgo).substring(0, 10),
      status: status,
      currentStepPosition: step,
      createdAt: iso(daysAgo, 8),
      attachments: [...attachments],
    );

    for (final (action, actorId, stepPos, ago, hour, comment, signed)
        in trail) {
      final actor = _user(actorId);
      final at = iso(ago, hour);
      _approvals.add(
        MockApproval(
          id: _nextApprovalId++,
          voucherId: id,
          stepPosition: stepPos,
          actorId: actorId,
          actorName: actor?.name ?? '—',
          action: action,
          actedAt: at,
          comment: comment,
          signature: signed ? actor?.signature : null,
        ),
      );
      if (action == 'submitted') v.submittedAt = at;
      if (action == 'approved') v.approvedAt = at;
      if (action == 'rejected') v.rejectedAt = at;
      if (action == 'paid') v.paidAt = at;
      if (action == 'signed' && signedAtStep) v.stepSignedAt = at;
    }

    v.paymentReference = paymentRef;
    v.paidBy = paidBy;
    v.payeeBank = bank;
    v.payeeAccountName = accountName;
    v.payeeAccountNumber = accountNumber;
    v.payeeBankBranch = bankBranch;
    v.cashFloat = float;
    v.receivedBy = receivedBy;
    _vouchers.add(v);
  }
}
