<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{ $title }}</title>
<style>
  @font-face { font-family: 'poppins'; font-weight: 400; src: url("{{ $fontPath }}/Poppins-Regular.ttf") format('truetype'); }
  @font-face { font-family: 'poppins'; font-weight: 600; src: url("{{ $fontPath }}/Poppins-SemiBold.ttf") format('truetype'); }
  @page { margin: 12mm 10mm 14mm; }
  body { font-family: 'poppins', sans-serif; font-size: 8pt; color: #201e1d; margin: 0; }
  .kicker { font-size: 6.4pt; letter-spacing: .1em; text-transform: uppercase; color: #605d5d; }
  h1 { font-size: 15pt; font-weight: 600; margin: 2pt 0 1pt; letter-spacing: -.01em; }
  .head { border-bottom: 2.4pt solid #201e1d; padding-bottom: 6pt; margin-bottom: 8pt; }
  table.data { width: 100%; border-collapse: collapse; }
  table.data th { text-align: left; font-size: 6.4pt; letter-spacing: .07em; text-transform: uppercase;
                  color: #605d5d; padding: 4pt 5pt; border-bottom: 0.7pt solid #201e1d; }
  table.data td { padding: 4pt 5pt; border-bottom: 0.4pt solid #eae7e7; }
  table.data tr:nth-child(even) td { background: #f8f4f4; }
  .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .summary { margin-top: 10pt; border-top: 1.2pt solid #201e1d; padding-top: 6pt; font-size: 8.4pt; }
  .foot { position: fixed; bottom: -8mm; left: 0; right: 0; font-size: 6.6pt; color: #605d5d; }
</style>
</head>
<body>

<table class="head">
  <tr>
    <td>
      <div class="kicker">{{ $company?->name ?? 'VouchFlow' }} · Report</div>
      <h1>{{ $title }}</h1>
      <div style="color:#605d5d;">{{ $range }} · {{ count($rows) }} rows</div>
    </td>
    <td style="text-align:right; vertical-align:bottom; color:#605d5d;">
      Generated {{ $generatedAt }}
    </td>
  </tr>
</table>

<table class="data">
  <thead>
    <tr>
      @foreach ($headings as $heading)
        <th @class(['num' => str_contains(strtolower($heading), 'amount') || str_contains(strtolower($heading), 'value') || str_contains(strtolower($heading), 'turnaround')])>{{ $heading }}</th>
      @endforeach
    </tr>
  </thead>
  <tbody>
    @forelse ($rows as $row)
      <tr>
        @foreach ($row as $cell)
          <td @class(['num' => is_numeric($cell) && ! is_string($cell)])>{{ is_float($cell) ? number_format($cell, 2) : $cell }}</td>
        @endforeach
      </tr>
    @empty
      <tr><td colspan="{{ count($headings) }}" style="text-align:center; padding:14pt; color:#7d7979;">No records matched these filters.</td></tr>
    @endforelse
  </tbody>
</table>

<div class="summary">
  <strong>{{ $summary['count'] }}</strong> vouchers ·
  Requested <strong>{{ $summary['total_text'] }}</strong> ·
  Approved <strong>{{ $summary['approved_total_text'] }}</strong>
</div>

<div class="foot">{{ $company?->name ?? 'VouchFlow' }} · Generated by VouchFlow · Confidential</div>

</body>
</html>
